baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

enableRobotsTXT: true

#services:
  #googleAnalytics:
    #id: G-MEASUREMENT_ID
  #disqus:
    #shortname: your-disqus-shortname

pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ruchira."
    subtitle: "I build things for the web"
    content: "A passionate team player, keen on working in a competitive and innovative environment, with more challenges by providing elegant solutions. Also, an energetic and skillful self-learner who is extremely good at building strong affinities with productive communication. Displays more interest in learning new technologies."
    image: /images/side_img.png
    button:
      enable: true
      name: "Resume"
      url: "/cv.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/RuchiraRuwantha
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ruchira-ruwantha/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a software developer with a passion for web development. I have experience in Javascript, Typescript, and front-end libraries like React and back-end server environments like Node.js and Javascript testing automation frameworks like Cypress. I am currently working as a software engineer at [Verdentra (Pvt) Ltd.](https://www.verdentra.com/).

      I am currently working on a project that is a Banking-as-a-Service (BaaS) platform which will enables digital businesses across various industries to offer embedded financial services to their underserved customers.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "TypeScript"
        - "JavaScript"
        - "React"
        - "SQL"
        - "Snowflake"
        - "Node.js"
        - "Express.js"
        - "HTML"
        - "CSS"
        - "Cypress"
        - "Jest"
        - "AWS"
        - "Java"

  # Experience
  experience:
    enable: true
    items:
      - job: "Software Engineer"
        company: "Verdentra"
        companyUrl: "https://www.Verdentra.com/"
        date: "Sept 2022 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          I am currently working as a software engineer (Remote) at [Verdenra](https://www.verdenra.com/) in New York.

          - Specialized in developing front‑end solutions using React and creating robust microservices with Node.js
          - Designed, developed, and deployed reusable, cross-browser compatible solutions, ensuring a seamless user experience across all platforms.
          - Partnered closely with team leads, designers, and product managers to deliver key features, driving the project forward through effective collaboration.
          - Gained substantial experience in core computer science principles, web development fundamentals, and agile methodologies.
          - Proficient in asynchronous programming, data structures, and solution design, ensuring efficient and scalable software development.
          - Engineered sleek UIs aligned with mock-ups, seamlessly integrated functionalities, and RESTful APIs for optimal performance.          

      - job: "Associate Software Engineer"
        company: "LiveRoom"
        companyUrl: "https://liveroom.xyz"
        date: "Mar 2021 - Sep 2022"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          I worked as an associate software engineer at [LiveRoom (Pvt) Ltd.](https://liveroom.xyz) in Colombo, Sri Lanka.

          - As a front-end engineer, spearheaded the design and development of pivotal software components with precision and innovation.
          - Crafted compelling UIs aligned with mock-ups, executing, troubleshooting, and refining functionalities for seamless user experiences.
          - Drove impactful research efforts to enhance software performance and ensure meticulous maintenance standards.
          - Engineered and seamlessly integrated test automation suites into the CI/CD pipeline for efficient and reliable software deployment.          

      - job: "Trainee Software Engineer"
        company: "LiveRoom"
        companyUrl: "https://liveroom.xyz"
        date: "2019 Feb – 2019 Aug"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a Trainee Software Engineer for more than 6 months in LiveRoom.
        content: |
          I worked as an Trainee Software Engineer at [LiveRoom (Pvt) Ltd.](https://liveroom.xyz) in Colombo, Sri Lanka for more than 6 months.

          - Worked as a front-end engineer. 
          - Had the opportunity to worked with different front-end languages and technologies like HTML, CSS, JavaScript, React, React
            Native, Material-UI etc. 
          - Worked on designing UIs, implementing functionalities etc.

      - job: "Freelance Developer"
        company: "Fiverr"
        companyUrl: "#"
        date: "2020 - Present"
        info:
          enable: true
          content: I am working as a Freelance Developer for nearly 2 years.
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I contributed to multiple projects of small to mid scale in these capacity.

          - Web development
          - API integration
          - Functionality implementation

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Science (Hons.) in Computing and Information Systems"
        school:
          name: "Sabaragamuwa University of Sri Lanka"
          url: "https://www.sab.ac.lk/"
        date: "2016 - 2021"
        content: |
          I Publiced two papers in international Conferences based on predicting the success of movies using both social media data and movie meta data.
            - [LSTM Based Approach for Classifying Twitter Posts for Movie Success Prediction](https://ieeexplore.ieee.org/document/9317163) (2020 International Conference on Decision Aid Sciences and Application (DASA)).
            - [LSTM and Ensemble Based Approach for Predicting the Success of Movies Using Metadata and Social Media](https://ieeexplore.ieee.org/document/9581601) (2021 International Conference on Innovation and Intelligence for Informatics, Computing, and Technologies (3ICT)).

  # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #       image: /images/achievement.jpg
  #     - title: Facebook Hackathon Winner
  #       content: Developed a product using Artificial Intelligence.
  #       image: /images/achievement.jpg
  #     - title: Hugo Profile
  #       content: Developed a theme and getting 1K+ downloads per month.
  #       url: "https://github.com/gurusabarish/hugo-profile"
  #       image: /images/achievement.jpg
  #     - title: Microsoft Imagine Runner
  #       content: We are developed a product which can help others.
  #     - title: Google Summer of Code
  #       content: Contributed to a open source project.
  #       url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Neem
        content: |
          Neem is a Banking-as-a-Service (BaaS) platform that provides B2B embedded finance and lending solutions to underserved communities in emerging markets. A team of experienced fintech entrepreneurs, technologists, and operators founded Neem to promote financial wellness for underbanked communities.

          - Primarily worked on B2B and B2C platforms, driving user interface implementation, functionality enhancement, and API integration for \\impactful digital experiences.
          - Directly collaborated with product owners for task planning and estimations, while spearheading the frontend team to deliver impactful results.
        image: /images/projects/profile.png
        featured:
          name: neem.io
          link: https://www.neem.io/
        badges:
          - "TypeScript"
          - "React"
          - "Redux"
          - "Ant Design"
          - "CSS"
          - "AWS"
      - title: Modjoul
        content: |
          Modjoul is a centralized management system for warehouses which can manage employees and devices.

          - Played a pivotal role in crafting primary UIs, integrating APIs within critical components, and executing API implementations with precision.
          - Collaborated closely with the R\&D team to develop a cutting-edge MetaOps React Application, seamlessly interfacing with a Unity Application for enhanced communication and rendering capabilities.
        image: /images/projects/profile.png
        featured:
          name: modjoul.com
          link: https://modjoul.com/
        badges:
          - "React"
          - "Ant Design"
          - "CSS"
          - "Javascript"
          - "Redux"
          - "Node.js"
          - "Docker"
          - "AWS"
      - title: OGMO
        content: |
          OGMO is a cloud platform specially developed for e-Commerce, enabling consumers to visualize products they buy through 3D and Augmented Reality.

          - Worked on implementing the UIs of the major components and integrating the APIs.
          - Worked in implementing functionalities & configuring the OGMO WordPress plugin.
          - Implemented an automated test suite using Cypress and integrated it into the CI/CD.
        image: /images/projects/profile.png
        featured:
          name: ogmo.xyz
          link: https://www.ogmo.xyz
        badges:
          - "React"
          - "Material-UI"
          - "CSS"
          - "Javascript"
          - "Node.js"
          - "Cypress"
          - "AWS"
      - title: Mintzilla
        content: |
          This is a platform where customers can mint NFTs, and view, buy, transfer and sell them.

          - Worked on implementing the UIs of the major components and integrating the APIs.
          - Researched on software improvement and maintenance.
          - Implemented an e2e test suite using Cypress and integrated it into the CI/CD.       
        badges:
          - "TypeScript"
          - "Next.js"
          - "Tailwind CSS"
          - "Moralis"
          - "Web3"
          - "Cypress"
          - "AWS"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

      - title: Centralised Order Management System
        content:
          Centralised Order Management system for ThinkingFoods company in Spain. This system integrate multiple e-commerce websites and provide centralised overview
          with an analytic platform. Feature rich system with delivery management, order management, user management, email and sms notifications.
        image: /images/projects/profile2.jpg
        featured:
          name: Thinking Foods
          link: https://manager.thinkingfoods.com
        badges:
          - "React"
          - "Semantic-UI"
          - "CSS"
          - "Javascript"
          - "Redux"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:gurusabarisha@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
